### ISSUE TITLE
<br> in Markdown

### ISSUE THREAD

**Issue by mermshaus** [php-de/php-de.github.io#119]
Hi.

Könnten wir vielleicht auf dieses „zwei oder mehr Leerzeichen am Zeilenende ergeben ein `<br>`“ (Regel aus dem Markdown-Format) verzichten?

Das kann alternativ zum Beispiel so geschrieben werden:

~~~
<div>
Zeile 1<br>
Zeile 2<br>
Zeile 3
</div>
~~~

(Oder eben in eine Liste umgewandelt werden oder so.)

Das ist zwar Teil des Formats und ich verstehe auch, warum das so spezifiziert ist (Lesbarkeit des unkompilierten Texts), aber ich bin ein großer Fan vom Entfernen von trailing whitespace beim Speichern.

**Comment by hausl** [comment]
*Deshalb fände ich es cool, wenn wir darauf verzichten könnten, diese Regel aus dem Markdown-Format anzuwenden, die auf zwei Leerzeichen am Zeilenende basiert.*

Ich versuche künftig dran zu denken, habe kein Problem damit!
