### ISSUE TITLE
Debugging-Leitfaden ist zu lange und unübersichtlich

### ISSUE THREAD

**Issue by hausl** [php-de/php-de.github.io#123]
Wir sollten den kürzen... alleine schon die Grafik zu Beginn ist vermultich für 90% der Leute ein Grund die Nerven weg zu schmeissen. Bin der Meinung die gehört entsorgt und der Leitfaden auf ein Minimum gekürzt - so wie es oft auch als Standardantwort a la phpforum.de zitiert wird... so ca. 20 Zeilen und feritg..

**Comment by mermshaus** [comment]
Ja, siehe auch hier:

- https://github.com/php-de/php-de.github.io/issues/106#issuecomment-72223628

Ich habe das neulich auf phpforum.de auch mal halb angesprochen (leider nicht verlinkbar), als es dort um die Erweiterung des Wikis ging. Ich denke, dass für die Forenarbeit eine FAQ-Seite in vielen Fällen ausreicht, die ungefähr so funktioniert (Demo):

- http://fiddle.jshell.net/59dyrfjp/25/show/light/#mysql

Funktionales „Design“, kurze Inhalte. Das ist auch das, was ich hier im Repo mit der FAQ-Seite so ein wenig erweitert/angefangen habe.

- http://php-de.github.io/jumpto/faq/

Bei den Standardantworten auf phpforum.de gibt es eben auch das Problem, dass die nicht wirklich verlinkbar sind. Die sind nur in dem einen Forum gut integrierbar. Das reicht mir nicht.

**Comment by hausl** [comment]
Dann sind wir uns ja einig ;) 

Die FAQ Seite hier ist vom Ansatz her sehr gut, die werde ich im Detail mal überarbeiten, dann sieht das im Grunde auch so aus wie dort: http://phpforum.de/forum/showthread.php?t=231095  Welche Lizenz ist auf die Texte? Knan man die "klauen"? Anonsten kann man mit dem hier schon gut was anfangen.. moment..  ich überarbete die mal. ..

**Comment by hausl** [comment]
Fertig... --> FAQ: http://php-de.github.io/jumpto/faq/

Das wäre die "übliche" Varainte der Darstellung hier .. "Besser"?
Gut Nacht!

**Comment by mermshaus** [comment]
> Welche Lizenz ist auf die Texte? Knan man die "klauen"?

Die Lizenz ist die GFDL 1.2. Die ist nicht kompatibel mit CC-BY-SA.

- http://phpforum.de/forum/showthread.php?t=217501
- https://wiki.creativecommons.org/GFDL_versus_CC-by-sa

Ich glaube zwar nicht, dass einer der Autoren auf phpforum.de ein unüberwindbares Problem damit hätte (kann ich auch bei Gelegenheit mal fragen, weil es da auch nur drei, vier Leute sind, die den Großteil verfasst haben), wenn wir wesentliche Inhalte aus den Standardantworten hierher übernehmen (und damit auch umlizenzieren) würden, aber einfach so geht es wohl „eigentlich“ nicht. IANAL.

OT:

Auch in diesem Kontext wäre es natürlich wieder absolut sinnvoll, wenn dieses Projekt hier nicht unter der php.de-Flagge laufen würde, sondern ein allgemeines Projekt der Gesamt-Community sein könnte.

In das Horn stoße ich allerdings seit über 3 Jahren und habe ja auch im Februar 2012 genau so eine Sache gestartet. Warum dann im August 2013 dieses Projekt begonnen wurde (das meiner Meinung nach in vielerlei Hinsicht weniger durchdacht war und ist), statt zumindest mal zu versuchen, die ohnehin geringen vorhandenen Ressourcen zu bündeln, ist mir bis heute eher unverständlich.

Immerhin habe ich es geschafft, dass die Inhalte hier brauchbar lizenziert werden und dass die Originalverfasser auch mal gefragt werden…

**Comment by hausl** [comment]
Gibt nun im FAQ die kurze Version von mermshaue, daher soweit erledigt.
