### ISSUE TITLE
Linktarget - blank ?

### ISSUE THREAD

**Issue by hausl** [php-de/php-de.github.io#129]
Sind derzeit mal so mal so, in der Contribute-Gudline ist dazu nichts vermerkt was ich gesehen habe, 

Das sollten wir definieren und in der Richtline auch erwähnen.

**Comment by mermshaus** [comment]
Neues Fenster/Tab öffnen, ist für mich eine Nutzer-Entscheidung. Ich bin also dafür, kein a.target-Attribut zu verwenden.

**Comment by hausl** [comment]
Seh ich auch so.. Ich war aus irgendeinen Grund bis vor kurzem der Meinung das mit HTML das traget Attribut sowieso rausgeflogen ist... aber das hab ich wohl nur geträumt. Ich werd das dann mal so durchgängig einbauen. Dann reicht auch in der CG (Contribute Guidline) auch ein kleiner Hinweis dazu, da dort kein "How-To" Code gelehrt werden muss.

**Comment by hausl** [comment]
erledigt
