### ISSUE TITLE
Verlinkbarkeit (der FAQ-Seite)

### ISSUE THREAD

**Issue by mermshaus** [php-de/php-de.github.io#89]
Hi.

Als wie final sind URLs wie http://php-de.github.io/general/faq.html#html-charset anzusehen? Also, bleibt das so oder ist geplant, da noch irgendwas zu verschieben? Es geht darum, ob es Sinn macht, Einträge von speziell der Seite etwa in Forenbeiträgen zu verlinken.

Ich hätte bei dem Artikel nichts dagegen, ihn in der Hierarchie eins nach oben zu holen: http://php-de.github.io/faq.html#html-charset. Wenn das nicht zur Organisation passt, ist das aber auch kein Problem.

Ich habe den Fokus dieser Issue mal absichtlich größtenteils auf die FAQ-Seite gelegt. Natürlich brauchen wir dahingehend aber insgesamt für alle Seiten einen Plan.

Mal gucken, was hier so an Kommentaren kommt.

Gruß

**Comment by mermshaus** [comment]
Ich hoffe, ihr seht das, wenn ihr hier noch mal schreibe.

Ich habe die internen Verlinkungen jetzt noch mal umgebaut. Vorher wurde den Links die `site.url` vorangestellt, also nach der Config hier `http://php-de.github.io/`. Das habe ich in der Form flexibler gestaltet, dass das Präfix nun der relative Pfad zum Wurzelverzeichnis des Webauftritts ist. Bei den `/jumpto/xy/`-Seiten ist das also durchgängig `../..`, weil es zwei Ebenen nach oben geht. Diesen relativen Pfad habe ich der Einfachheit halber als Front-Matter-Setting `root` den einzelnen Seiten hinzugefügt. Ich habe mit anderen Optionen experimentiert, aber das scheint der sinnvollste Weg zu sein.

Es ändert sich dadurch nur, dass `{{ site.url }}` jetzt in Fällen der internen Verlinkung `{{ page.root }}` heißen muss und dass jede Seite eben das Setting `root` setzen muss. Ich habe die Contribute-Richtlinien entsprechend ergänzt.

Das hat den Vorteil, dass das Projekt auf einem lokalen System gebaut (`jekyll build`) und auch betrachtet werden kann (auf einem lokalen Webserver), ohne die `_config.yml` anpassen zu müssen oder mit `hosts`-Einstellungen rumzutricksen. Anders gesagt: Es ist jetzt egal, wo die generierten HTML-Dateien liegen. Es funktioniert überall, weil die Pfadangaben jetzt relativ sind.

Der entsprechende Commit verändert nur deshalb so viele Zeilen, weil durch meine Anpassungen etwaiger trailing whitespace entfernt wurde. Prinzipiell wurden aber nur die `root`-Zeilen ergänzt. Stellt eure Editoren so ein, dass sie trailing whitespace von sich aus on save entfernen. ;-)

Ich habe bewusst `../..` ohne trailing slash gewählt, damit die „statischen“ Pfadanteile, die auf ein `{{ page.root }}` folgen, immer mit einem Slash beginnen können. Das kann ich auf Wunsch noch genauer erklären. Die Idee ist grundsätzlich dieselbe wie hier:

- http://www.php.de/php-einsteiger/87765-pfade-normalisieren-kanonisieren.html

**Comment by hausl** [comment]
Hi,

- also ich wurde per Mail benachrichtigt
- finde den Grundgedanken gut, auch bzgl. der lokalen möglichen Verfügbarkeit

ABER:

> Der entsprechende Commit verändert nur deshalb so viele Zeilen, weil durch meine Anpassungen etwaiger trailing whitespace entfernt wurde.

Muss ich mal schauen, aber es gab doch auch einige "absichtliche" Umbrüche [blank][blank][br] die du damit "weg-optimiert" hast ?

**Comment by mermshaus** [comment]
Kann schon sein. Das wäre dann wieder Issue #119.

Wenn man das Diff zu d2196cb5 mal ein wenig durchgeht, stellt man aber auch fest, dass da doppelte Leerzeichen weggefallen sind, die „falsch“ waren, weil der zugehörige Abschnitt schon lange als Liste formatiert wurde.

Ich sehe da grundsätzlich nur eine Alternative:

1. Von Leuten verlagen, dass sie sich sehr bewusst sind, was Whitespace angeht und wo und warum sie welchen setzen.
2. Nach Möglichkeit `\n` und *remove trailing whitespace on save* verwenden und Markdown-Linebreaks – sofern überhaupt notwendig – mit HTML-`<br>` kodieren.

Punkt 1 ist keine Alternative, weil das nicht passieren wird. :)

**Comment by hausl** [comment]
Richtig, ich wollte auch "künftig" daran denken das zu verwenden ;)
https://github.com/php-de/php-de.github.io/issues/119#issuecomment-76061159

Dann kommt jetzt halt auch die Vergangenheitsbewältigung... Und meinen Editor hab ich jetzt auch umgestellt.
